spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Vu Khanh - QA Lead"
    email: "vukhanh@gmail.com"
  onCallSupport:
    - (777) 123-456
    - (777) 456-789