spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "vantu - Product Owner"
    email: "vantu@gmail.com"
  onCallSupport:
    - (666) 123-456
    - (666) 456-789